########################
##       ONJOIN       ##
########################


# Select locale of OnJoin, default it's English.
# Available locales:
#    default - English language. Uses 'language.yml'.
#    de - Deutsch
locale: default


########################
##        MySQL       ##
########################


#Do you want to use a MySQL database?
MySQL:
  Enabled: false
  #Should the MySQL connection reconnect after amount of time?
  AutoReconnect: false
    #Time in Minutes
    ReconnectCoolDown: 45
  Username: accountname
  Password: password
  Database: database
  Host: localhost
  Port: '3306'


########################
##     First Join     ##
########################


#Here you can enable FirstJoin stuff
FirstJoin:
  Enabled: false
  #Titel in the middle of the screen
  Title:
    TitleOnJoin: true
  #Welcome Message in the Chat
  WelcomeMessage:
    WelcomeMessageOn: true
  #Should there be a message to all players when a player enters the server
  Join:
    #Should it sends a message to Player with the Permission
    UpdateMessageOn: true
    #Should the chat be cleaned up by the player at the beginning?
    ChatClearOn: true
    #Should the Player with Permission OnJoin.* or OnJoin.Firework have a Firework when he joins?
    FireworkOn: true
    Firework:
      InstantExplode: false
      Amount: 3
      FireworkHeight: 3
      Power: 1
      Type: BALL
      Flicker: false
      Trail: false
      Colors:
      - YELLOW
      Fade:
      - WHITE
    JoinMessageOn: true
    #Should there be a sound
    JoinSoundOn: false
    JoinSound: FIREWORK_LAUNCH
  #Should the Player that join heal
  Heal:
    HealOn: true
    Health: 20
    FoodLevel: 20
    ClearPotionEffects: true
    #Should the Player that join with Permission heal
    HealOnWithPermission: true
    HealthWithPermission: 20
    FoodLevelWithPermission: 20
    ClearPotionEffectsWithPermission: true
  #Execute Commands after Join
  ExecuteCommand:
    CommandOn: false
    Commands:
    - 'console;say %player% Hello! Change this in Config!'
    - 'player;help'
  #Message on the actionbar
  Actionbar:
    ActionbarOnJoin: true
  #Should there be a message to all players when a player leaves the server
  Quit:
    QuitMessageOn: true
    #Should there be a sound
    QuitSoundOn: false
    QuitSound: BAT_DEATH
  #Should Players that join be teleported to a location
  SpawnLocation:
    SpawnLocationEnable: false
    World: world
    XCoord: 0
    YCoord: 0
    ZCoord: 0
    Yaw: 0
    Pitch: 0


########################
##    Normal Join     ##
########################


#Titel in the middle of the screen
Title:
  TitleOnJoin: true


#Welcome Message in the Chat
WelcomeMessage:
  WelcomeMessageOn: true


#Should there be a message to all players when a player enters the server
Join:
  #Should it sends a message to Player with the Permission
  UpdateMessageOn: true
  #Should the chat be cleaned up by the player at the beginning?
  ChatClearOn: true
  #Should the Player with Permission OnJoin.* or OnJoin.Firework have a Firework when he joins?
  FireworkOn: true
  Firework:
    InstantExplode: false
    Amount: 3
    FireworkHeight: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
    - YELLOW
    Fade:
    - WHITE
  JoinMessageOn: true
  #Should there be a sound
  JoinSoundOn: false
  JoinSound: FIREWORK_LAUNCH


#Should the Player that join heal
Heal:
  HealOn: true
  Health: 20
  FoodLevel: 20
  ClearPotionEffects: true
#Should the Player that join with Permission heal
  HealOnWithPermission: true
  HealthWithPermission: 20
  FoodLevelWithPermission: 20
  ClearPotionEffectsWithPermission: true


#Execute Commands after Join
ExecuteCommand:
  CommandOn: false
  Commands:
    - 'console;say %player% Hello! Change this in Config!'
    - 'player;help'


#Message on the actionbar
Actionbar:
  ActionbarOnJoin: true


#Should there be a message to all players when a player leaves the server
Quit:
  QuitMessageOn: true
  #Should there be a sound
  QuitSoundOn: false
  QuitSound: BAT_DEATH


#Should Players that join be teleported to a location
SpawnLocation:
  SpawnLocationEnable: false
  World: world
  XCoord: 0
  YCoord: 0
  ZCoord: 0
  Yaw: 0
  Pitch: 0


##########################
##     DON´T MODIFY     ##
##########################


# Don't modify.
Version: 3

# No way! You've reached the end! Let us join!?