########################
##       ONJOIN       ##
########################


# Select locale of OnJoin, default it's English.
# Available locales:
#    default - English language. Uses 'language.yml'.
#    de - Deutsch
locale: default


# Should the plugin send debug messages into console? | This mode can be good to find bugs!
debug: false


########################
##        MySQL       ##
########################


#Do you want to use a MySQL database?
MySQL:
  Enabled: false
  #Should the MySQL connection reconnect after amount of time?
  AutoReconnect:
    Enabled: false
    #Time in Minutes
    ReconnectCoolDown: 45
  Username: accountname
  Password: password
  Database: database
  Host: localhost
  Port: '3306'


################################
##     First Join Settings    ##
################################


#Here you can enable FirstJoin stuff
FirstJoin:
  Enabled: false
  #Titel in the middle of the screen
  Title:
    TitleOnJoin: true
  #Message on the actionbar
  Actionbar:
    ActionbarOnJoin: true


##########################
##    Join Settings     ##
##########################

#Titel in the middle of the screen
Title:
  TitleOnJoin: true

#Should there be a message to all players when a player enters the server
Join:
  #Should it sends a message to Player with the Permission
  UpdateMessageOn: true

#Message on the actionbar
Actionbar:
  ActionbarOnJoin: true


###################
##     Spawn     ##
###################


#Should Players that join be teleported to a location
SpawnLocation:
  'default':
    Enabled: false
    World: world
    XCoord: 0
    YCoord: 0
    ZCoord: 0
    Yaw: 0
    Pitch: 0
  'firstjoin':
    Enabled: false
    World: world
    XCoord: 0
    YCoord: 0
    ZCoord: 0
    Yaw: 0
    Pitch: 0
  '1':
    Permission: OnJoin.Spawn.1
    World: world
    XCoord: 0
    YCoord: 0
    ZCoord: 0
    Yaw: 0
    Pitch: 0


######################
##     Commands     ##
######################


#Execute commands after join
ExecuteCommand:
  'default':
    Enabled: false
    Commands:
      - 'console;say %player% Hello! Change this in Config!'
      - 'player;help'
  'firstjoin':
    Enabled: false
    Commands:
      - 'console;say %player% Hello! Change this in Config!'
      - 'player;help'
  '1':
    Permission: OnJoin.ExecuteCommand
    Commands:
      - 'console;say %player% Hello! Change this in Config!'
      - 'player;help'


##################
##     Heal     ##
##################


#Should the Player that join heal
Heal:
  'default':
    Enabled: true
    Health: 20
    FoodLevel: 20
    ClearPotionEffects: true
  'firstjoin':
    Enabled: true
    Health: 20
    FoodLevel: 20
    ClearPotionEffects: true
  '1':
    Permission: OnJoin.Heal.1
    Health: 20
    FoodLevel: 20
    ClearPotionEffects: true


######################
##     Firework     ##
######################

Firework:
  #Should a player have a Firework when he joins?
  'default':
    Enabled: true
    InstantExplode: false
    Amount: 3
    FireworkHeight: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
      - YELLOW
    Fade:
      - WHITE
  'firstjoin':
    Enabled: true
    InstantExplode: false
    Amount: 3
    FireworkHeight: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
      - YELLOW
    Fade:
      - WHITE
  #Should a player with custom permission have a Firework when he joins?
  '1':
    Permission: OnJoin.Firework.1
    InstantExplode: false
    Amount: 3
    FireworkHeight: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
      - YELLOW
    Fade:
      - WHITE


####################
##     Sounds     ##
####################

Sounds:
  Join:
    'default':
      Enabled: true
      Sound: FIREWORK_LAUNCH
      Volume: 1
      Pitch: 1
    'firstjoin':
      Enabled: true
      Sound: FIREWORK_LAUNCH
      Volume: 1
      Pitch: 1
    '1':
      Permission: OnJoin.JoinSound.1
      Sound: FIREWORK_LAUNCH
      Volume: 1
      Pitch: 1
  Quit:
    'default':
      Enabled: true
      Sound: BAT_DEATH
      Volume: 1
      Pitch: 1
    'firstjoin':
      Enabled: true
      Sound: BAT_DEATH
      Volume: 1
      Pitch: 1
    '1':
      Permission: OnJoin.QuitSound.1
      Sound: BAT_DEATH
      Volume: 1
      Pitch: 1



##########################
##     DON´T MODIFY     ##
##########################


# Don't modify.
Version: 6


# No way! You've reached the end! Let us join!?