########################
##       ONJOIN       ##
########################


# Select locale of OnJoin, default it's English.
# Available locales:
#    default - English language. Uses 'language.yml'.
#    de - Deutsch
locale: default


# Should the plugin send debug messages into console? | This mode can be good to find bugs!
debug: false


########################
##        MySQL       ##
########################


#Do you want to use a MySQL database?
MySQL:
  Enabled: false
  #Should the MySQL connection reconnect after amount of time?
  AutoReconnect:
    Enabled: false
    #Time in Minutes
    ReconnectCoolDown: 45
  Username: accountname
  Password: password
  Database: database
  Host: localhost
  Port: '3306'


################################
##     First Join Settings    ##
################################


#Here you can enable FirstJoin stuff
FirstJoin:
  Enabled: false


##########################
##    Join Settings     ##
##########################


#Enable join update message (only with the update permission)
Join:
  UpdateMessageOn: true


####################################
##     Additional Information     ##
####################################


#For better understanding I will try to explain the following configuration parts!
#In every section you can add 'default' and 'firstjoin'
#They will be the ground function: firstjoin for firstjoin and default for default
#The categories default and firstjoin you can Enable with true
#The other categories that you can self add like you want become the option to set a Permission
#If you don´t need more than default and firstjoin feel free to remove the category '1'
#You can add as much categories as you like! But please keep in mind to order it in the right way:
#It should be default and firstjoin first after that the highest permission because the plugin is checking the
#permissions. It will search for every permission that the user have, so it would only work right if you
#add the category with the highest rank above the others that you add
#Possible questions:
#Why is there no Enable function for self added categories?
# - You don´t need an enable function because the added categories will automatically enabled
# - If you not need one of your categories you can remove them to disable or give a permission that no one has

###################
##     Spawn     ##
###################


#Should Players that join be teleported to a location
SpawnLocation:
  'default':
    Enabled: false
    World: world
    XCoord: 0
    YCoord: 0
    ZCoord: 0
    Yaw: 0
    Pitch: 0
  'firstjoin':
    Enabled: false
    World: world
    XCoord: 0
    YCoord: 0
    ZCoord: 0
    Yaw: 0
    Pitch: 0
  '1':
    Permission: OnJoin.Spawn.1
    World: world
    XCoord: 0
    YCoord: 0
    ZCoord: 0
    Yaw: 0
    Pitch: 0


######################
##     Commands     ##
######################


#Execute commands after join
ExecuteCommand:
  'default':
    Enabled: false
    Commands:
      - 'console;say %player% Hello! Change this in Config!'
      - 'player;help'
  'firstjoin':
    Enabled: false
    Commands:
      - 'console;say %player% Hello! Change this in Config!'
      - 'player;help'
  '1':
    Permission: OnJoin.ExecuteCommand
    Commands:
      - 'console;say %player% Hello! Change this in Config!'
      - 'player;help'


##################
##     Heal     ##
##################


#Should the Player that join heal
Heal:
  'default':
    Enabled: true
    Health: 20
    FoodLevel: 20
    ClearPotionEffects: true
  'firstjoin':
    Enabled: true
    Health: 20
    FoodLevel: 20
    ClearPotionEffects: true
  '1':
    Permission: OnJoin.Heal.1
    Health: 20
    FoodLevel: 20
    ClearPotionEffects: true


######################
##     Firework     ##
######################


Firework:
  #Should a player spawn a Firework when he joins?
  'default':
    Enabled: true
    InstantExplode: false
    Amount: 3
    FireworkHeight: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
      - YELLOW
    Fade:
      - WHITE
  'firstjoin':
    Enabled: true
    InstantExplode: false
    Amount: 3
    FireworkHeight: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
      - YELLOW
    Fade:
      - WHITE
  #Should a player with custom permission spawn a Firework when he joins?
  '1':
    Permission: OnJoin.Firework.1
    InstantExplode: false
    Amount: 3
    FireworkHeight: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
      - YELLOW
    Fade:
      - WHITE


####################
##     Sounds     ##
####################


Sounds:
  Join:
    'default':
      Enabled: true
      Sound: ENTITY_FIREWORK_BLAST
      Volume: 1
      Pitch: 1
    'firstjoin':
      Enabled: true
      Sound: ENTITY_FIREWORK_BLAST
      Volume: 1
      Pitch: 1
    '1':
      Permission: OnJoin.JoinSound.1
      Sound: ENTITY_FIREWORK_BLAST
      Volume: 1
      Pitch: 1
  Quit:
    'default':
      Enabled: true
      Sound: ENTITY_BAT_DEATH
      Volume: 1
      Pitch: 1
    'firstjoin':
      Enabled: true
      Sound: ENTITY_BAT_DEATH
      Volume: 1
      Pitch: 1
    '1':
      Permission: OnJoin.QuitSound.1
      Sound: ENTITY_BAT_DEATH
      Volume: 1
      Pitch: 1




##########################
##     DON´T MODIFY     ##
##########################


# Don't modify.
Version: 9999999


# No way! You've reached the end! Let us join!?