#Alle Consolen-Nachrichten
Console:
  PrefixConsole: '&7[&eOnJoin&7]'
  newupdatebconrl: 'Neue Version verfügbar! Downloade sie dir auf SpigotMC!'
#Nachrichten - Command OnJoin
Help:
  HelpText:
    - ''
    - '&e--------- &7[&aHILFE &7| &eOnJoin&7]&e ---------'
    - '&e|  '
    - '&e|  &7/&eonjoin'
    - '&e|    &c->  &7Übersicht'
    - '&e|  '
    - '&e|  &7/&eonjoin &areloadconfig'
    - '&e|    &c->  &7Lade deine Config neu'
    - '&e|  '
    - '&e|  &7/&eonjoin &asetspawn'
    - '&e|    &c->  &7Setze die Spawnlocation'
    - '&e|  '
    - '&e--------- &7[&aHILFE &7| &eOnJoin&7]&e ---------'
    - ''
  OutConfigCreate: 'Eine Config wurde im Plugin-Ordner erstellt!'
  OutConfigLoad: 'Die Einstellungen aus der Config wurden erfolgreich geladen!'
#Allgemeine Nachrichten
Prefix: '&7[&eOnJoin&7] &7»&e '
Permissionfail: '&cDafür hast du keine Rechte'
TargetFalse: '&cDer Spieler ist momentan &enicht online &coder wurde &efalsch geschrieben'
NoPlayer: 'Du bist kein Spieler'
#Titel in der Mitte des Screens
Title:
  TitleOnJoin: true
  Title1: '&bCC&3SW'
  SubTitle1: '&eOnJoin'
  SubTitle2: '&aTitle&8 - &7Kann in der &8onjoin.yml &7editiert werden'
#Willkommens Nachricht im Chat
WelcomeMessage:
  WelcomeMessageOn: true
  #Du kannst beliebig viele Zeilen hinzufügen und entfernen!
  WelcomeMessageText:
    - '&e------------------------------------'
    - '&e|  '
    - '&e|  Heey, &a%player%&7!'
    - '&e|  &eWillkommen auf unseren Server!'
    - '&e|  '
    - '&e|  &eOnJoin &8- &7Dein Join Plugin'
    - '&e|  &7Plugin by &bTigerpanzer_02/Tigerkatze'
    - '&e|  &7Dein Netzwerk @CC-SW'
    - '&e|  '
    - '&e------------------------------------'
#Soll es eine Nachricht an alle Spieler geben, wenn ein Spieler den Server betritt
Join:
  #Soll es eine Nachricht an einen Spieler mit Permission schicken
  UpdateMessageOn: true
  UpdateMessageText:
  - '&e--------- &7[&aUPDATE &7| &eOnJoin&7]&e ---------'
  - '&c|  Neues Update verfügbar! Du kannst es dir'
  - '&c|  auf SpigotMC herunterladen!'
  - '&c|  https://www.spigotmc.org/resources/56907/'
  - '&e--------- &7[&aUPDATE &7| &eOnJoin&7]&e ---------'
  #Soll der Chat vom Spieler am Anfang bereinigt werden
  ChatClearOn: true
  #Soll wenn ein Spieler mit der Permission OnJoin.* oder OnJoin.Firework den Server betretet ein Feuerwerk beim Spieler erscheinen?
  Firework-On: true
  Firework:
    Instant-Explode: false
    Amount: 3
    Firework-Height: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
    - YELLOW
    Fade:
    - WHITE
  JoinMessageOn: true
  JoinMessage: '&7%player% hat den Server betreten'
  #Soll es einen Ton geben
  JoinSoundOn: false
  JoinSound: FIREWORK_LAUNCH
#Soll der Spieler geheilt werden
Heal:
  HealOn: true
  Health: 20
  FoodLevel: 20
  ClearPotionEffects: true
#Soll der Spieler mit Permissions geheilt werden
  HealOnWithPermission: true
  HealthWithPermission: 20
  FoodLevelWithPermission: 20
  ClearPotionEffectsWithPermission: true
#Führe Commands nach dem Joinen aus
ExecuteCommand:
  CommandOn: false
  Commands:
  - 'console;say %player% Hallo! Ändere es in der Config!'
  - 'player;help'
#Nachricht in der Actionbar
actionbar:
  actionbaronjoin: true
  actionbar1: '&7%player%! Willkommen'
  actionbar2: '&7 CC-SW Network'
#Soll es eine Nachricht an alle Spieler geben, wenn ein Spieler den Server verlässt
Quit:
  QuitMessageOn: true
  QuitMessage: '&7%player% hat den Server verlassen'
  #Soll es einen Ton geben
  QuitSoundOn: false
  QuitSound: BAT_DEATH
#Sollen Spieler die joinen an eine Position teleportiert werden
SpawnLocation:
  SpawnLocationEnable: false
  World: world
  XCoord: 0
  YCoord: 0
  ZCoord: 0
  Yaw: 0
  Pitch: 0
  SetSpawnMessageSetTo: '&aSpawn gesetzt zu&7: '
  SetSpawnMessageYaw: '&2Yaw&7: '
  SetSpawnMessagePitch: '&2Pitch&7: '