name: OnJoin
author: Tigerpanzer (SpigotMC Tigerkatze) [CC-SW Network]
main: at.tigerpanzer.onjoin.Main
version: ${project.version}
description: With this plugin, joins are unique on your server
softdepend: [PlaceholderAPI]
commands:
  onjoin:
    description: Main command

permissions:
  OnJoin.*:
    description: Gives you all permissions for OnJoin
    children:
      OnJoin.Firework: true
      OnJoin.config: true
      OnJoin.UpdateMessage: true
      OnJoin.ExecuteCommand: true
      OnJoin.Heal: true