name: OnJoin
author: Tigerpanzer (SpigotMC Tigerkatze) [CC-SW Network]
main: main.java.at.tigerpanzer.onjoin.Main
version: 2.0.0TESTINGSTAGE
description:
softdepend: [PlaceholderAPI]
commands:
  onjoin:  
